### ISSUE TITLE
dialog-dismiss attribute on paper-icon-button not working with paper-dialog

### ISSUE THREAD

**Issue by RebeccaStevens** [PolymerElements/paper-dialog#87] opened 2016-02-03 05:49 UTC
When the `dialog-dismiss` attribute is added to a `paper-icon-button`, clicking the button does not close the `paper-dialog`.

```
<paper-dialog>
  <paper-icon-button icon="icons:cancel" title="Close" dialog-dismiss></paper-icon-button>
  ...
</paper-dialog>
```

Note: Using the Inspector, if I add the `dialog-dismiss` attribute to the `iron-icon` in the `paper-icon-button`'s dom then click the button, it will close.

PolymerElements/paper-icon-button#70

**Comment by valdrinkoshi** [comment] 2016-02-03 19:30
Closing this as its a duplicate of https://github.com/PolymerElements/paper-dialog-behavior/issues/66

**Closed as completed by valdrinkoshi** 2016-02-03 19:30 UTC
