### ISSUE TITLE
paper-dialog closes when you click on it

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dialog#39] opened 2015-09-25 11:04 UTC
`paper-dialog` now automatically closes when you click over it (on every part, it even closes if you click on a `paper-input` to write some text). This is probably caused by some recent change to the `iron-overlay-behavoir`, I suspect.

**Comment by samccone** [comment] 2015-09-25 15:06
@kungufli What device are you testing this one?

**Comment by kungufli** [comment] 2015-09-25 15:10
I'm testing in Chrome 45.0.2454.101 on a Linux machine. The problem appeared today after I bower updated the bower_components.

**Comment by samccone** [comment] 2015-09-25 15:12
kk thanks for the debug info @kungufli !

**Comment by ebidel** [comment] 2015-09-25 15:16
@azakus @cdata did https://github.com/PolymerElements/iron-overlay-behavior/commit/ad1cda00708d1a79539b7ef511454d576ed779f6 break this?

**Comment by kungufli** [comment] 2015-09-28 10:23
Seems fixed for me after today bower update. Thanks.

**Comment by ebidel** [comment] 2015-09-28 14:55
@cdata Shall we close?

**Comment by valdrinkoshi** [comment] 2015-12-08 19:25
Tested again, the issue is fixed in `v1.0.3`. Closing this

**Closed as completed by valdrinkoshi** 2015-12-08 19:25 UTC

**Comment by cineq** [comment] 2016-11-08 21:32
Hi I am facing with same issue described here. I am using master version
