### ISSUE TITLE
paper-dialog Closed Immediately After Opening

### ISSUE THREAD

**Issue by putraxor** [PolymerElements/paper-dialog#17] opened 2015-06-25 04:02 UTC
paper-dialog closed immediately after opening that triggered by on-tap event.
When I replace the event by on-click, everything works.

```
<dom-module id="form-signin">
    <style>
        a {
            color: #3F51B5;
            text-decoration: none;
        }
    </style>
    <template>
        <paper-dialog id="alert" entry-animation="scale-up-animation" exit-animation="fade-out-animation">
            <h2>Login</h2>
            <div>Username dan password yang anda masukkan salah, silahkan coba lagi</div>
            <div class="buttons">
                <paper-button dialog-confirm autofocus>Tutup</paper-button>
            </div>
        </paper-dialog>
        <paper-card heading="Administrator" image="images/card-image/login.jpg">
            <p>Silahkan masukkan username dan password anda:</p>
            <paper-input label="Username" value="{{username}}"></paper-input>
            <paper-input label="Password" type="password" value="{{password}}"></paper-input>
            <p>
                <paper-button on-tap="signIn" raised>Sign In</paper-button>
                <paper-button on-tap="reset" raised>Reset</paper-button>
            </p>
        </paper-card>
    </template>
</dom-module>
<script>
    (function () {
        Polymer({
            is: 'form-signin',
            properties: {
                invalid: false,
                username: '',
                password: ''
            },
            reset: function () {
                this.username = '';
                this.password = '';
            },
            signIn: function () {
                if (this.username == 'admin' && this.password == '12345') {
                    localStorage.setItem("has_login", "yes");
                } else {
                    this.invalid = true;
                    this.reset();
                    this.$.alert.open();
                }
            }

        });
    })();
</script>
```

**Comment by rubenstolk** [comment] 2015-06-29 05:39
+1

**Comment by vescoyez** [comment] 2015-06-30 12:57
+1 on safari mobile

**Comment by blerest** [comment] 2015-07-02 15:29
+1

**Comment by ghost** [comment] 2015-07-08 14:06
+1 and thanks @putraxor for the quick fix

PS. To me, it only happened from Chrome mobile on a Nexus 5. 
It's all good from Chrome desktop.

---

Actually, if you have a `paper-input` inside the dialog, it disappears on mobile. Even if you open it from a click event ;(

Any quick workaround for that?

**Comment by rubenstolk** [comment] 2015-07-09 02:00
Similarly to issue #7 I've changed my patch to be like:

``` js
// https://github.com/PolymerElements/paper-dialog/issues/7
patchOverlay: function (e) {
  if (e.target.withBackdrop) {
    e.target.parentNode.insertBefore(e.target._backdrop, e.target);
    if (!e.target.modal) {
      e.target.noCancelOnOutsideClick = true;
      setTimeout(function () {
        e.target.noCancelOnOutsideClick = false;
      }, 400);
    }
  }
},
```

Basically if the modal does have a backdrop but does not have the modal property, I toggle the noCancelOnOutSideClick on for just the 400ms to prevent the tap on the original button to slip through... Hope this helps anyone, it's still a hack of course...

**Comment by ghost** [comment] 2015-07-13 11:05
@rubenstolk 's fix doesn't work on my dialog. Please fix!

PS. Could be useful for the fix: If I press `tab` after the dialog is opened, then it won't close anymore when I click the `paper-input`s inside.
I still have to open it `on-click`though, bc when I open it `on-tap`, it will close as soon as it opens.

~~So, an hack-ish way to solve it temporarily would be to open it `on-click` and simulate a `tap` press as soon as the dialog opens.~~

EDIT: Just calling `this.$.inputId.focus();` in the `ready` callback of the dialog element seems to solve the closing issue when you click on an input!

**Comment by Mygod** [comment] 2015-07-14 00:44
+1

**Comment by nicholas-brandt** [comment] 2015-07-21 10:34
+1

**Comment by ronnyroeller** [comment] 2015-07-23 22:32
+1

**Comment by ajit-kumar-azad** [comment] 2015-07-27 21:08
+1

**Comment by kungufli** [comment] 2015-07-28 15:08
+1

**Comment by spirylics** [comment] 2015-08-17 19:53
+1

**Comment by Anthony2539** [comment] 2015-08-18 06:38
+1

**Comment by alexandrubichis** [comment] 2015-08-28 06:47
+1

**Comment by tdesc** [comment] 2015-09-05 08:04
+1 Very critical. Makes any mobile app unusable. 
This is common issue for Iron-Overlay-Behaviour. To see it, just turn on Chrome mobile simulation in Chrome desktop.

Solution, what fix this issue offered by @himu62
https://github.com/PolymerElements/iron-overlay-behavior/issues/14

**Comment by jptrainor** [comment] 2015-09-14 23:51
+1

**Comment by elegant651** [comment] 2015-09-26 16:18
+1

**Comment by samccone** [comment] 2015-09-26 18:36
xref 
https://github.com/PolymerElements/paper-dialog/issues/39

**Comment by valdrinkoshi** [comment] 2015-12-04 22:32
Cannot reproduce it (tested in chrome desktop and safari mobile) 
http://jsbin.com/gagage/21/edit?html,output

**Closed as completed by valdrinkoshi** 2015-12-04 22:32 UTC
