### ISSUE TITLE
backdrop dialog display behind overlay if used in header-panel within custom element

### ISSUE THREAD

**Issue by itboy87** [PolymerElements/paper-dialog#7] opened 2015-05-28 13:24 UTC
i created new custom element and add backdrop paper-dialog child in it.From main file i used that custom element in paper-header-panel when dialog opened card goes behind the overlay.
From inspecting elements if uncheck the "z-index:0" property of paper-header-panel then dialog show on top as normal.
![polymer-backdrop](https://cloud.githubusercontent.com/assets/11086988/7860954/adef3fe4-0566-11e5-9a88-cf1318dae234.JPG)

**Comment by morethanreal** [comment] 2015-05-28 20:43
Need https://github.com/PolymerElements/iron-overlay-behavior/issues/3.

For now, you should place the dialog at the top level if possible to avoid stacking context issues.

**Comment by dhpollack** [comment] 2015-06-19 06:24
I solved this by moving the backdrop element directly before the dialog element.

iron-overlay-behavior.html line 325:

``` javascript
    _finishRenderOpened: function() {
      // focus the child node with [autofocus]
      if (!this.noAutoFocus) {
        this._focusNode.focus();
      }

      if(this.withBackdrop) {
        this.parentNode.insertBefore(this._backdrop, this);
      }

      this.fire('iron-overlay-opened');

      this._squelchNextResize = true;
      this.async(this.notifyResize);
    },

```

**Comment by gertcuykens** [comment] 2015-06-25 19:35
+1

**Comment by gertcuykens** [comment] 2015-06-25 21:47
@dhpollack this almost work except that it doesn't look good when using entry-animation="scale-up-animation" exit-animation="fade-out-animation"

**Comment by jannakha** [comment] 2015-06-26 01:43
Also, if paper-dialog is placed inside a sized element, it will be sized according to the parent element, not full screen browser window, although it will be rendered in the middle of the screen. I would expect dialog box' size to be relative to full screen display - see attachments (same dialog box - different parent elements dimensions)

![screen shot 2015-06-26 at 11 41 34 am](https://cloud.githubusercontent.com/assets/1356783/8369120/61c3795c-1bf8-11e5-861e-1b568190f362.png)
![screen shot 2015-06-26 at 11 41 44 am](https://cloud.githubusercontent.com/assets/1356783/8369121/61c73e7a-1bf8-11e5-8e2f-653fa8ba9f7b.png)

**Comment by kbwatts** [comment] 2015-07-03 04:36
+1

**Comment by rubenstolk** [comment] 2015-07-04 10:03
To implement @dhpollack's hack in a nice way, add this function to your custom element:

``` js
// https://github.com/PolymerElements/paper-dialog/issues/7
patchOverlay: function (e) {
  if (e.target.withBackdrop) {
    e.target.parentNode.insertBefore(e.target._backdrop, e.target);
  }
},
```

And add `on-iron-overlay-opened="patchOverlay"` to all your `<paper-dialog>`'s

**Comment by ConAntonakos** [comment] 2015-07-08 21:55
Thanks, @rubenstolk. I'm adding that block of logic to the callback, `'iron-overlay-closed'`. Unfortunately, it seems to cause a flash on the page before settling. It could be the way that the HTML elements are composed, i.e., absolutely positioned elements, but I wanted to see if this has been working well for others. Thanks again!

**Comment by rubenstolk** [comment] 2015-07-09 01:44
It has to go to the `iron-overlay-opened` callback, not the `closed` one... No flashing here...

**Comment by ConAntonakos** [comment] 2015-07-09 14:36
Yeah, oops. I meant to say `iron-overlay-opened`. Ok; thank you. Could be the way the HTML elements are styled.

**Comment by rubenstolk** [comment] 2015-07-20 17:46
The given patch doesn't entirely solve the issue for iOS Safari where the header bar will still be visible over the backdrop in this case...

I went for this implementation in my root node ready function:

``` js
      var dialogs = this.querySelectorAll('paper-dialog');
      var first = this.childNodes[0];
      for (var i = dialogs.length - 1; i >= 0; i--) {
        this.insertBefore(dialogs[i], first);
      }
```

**Comment by Mygod** [comment] 2015-07-21 15:17
Just noticed that this issue has been resolved in paper-header-panel 1.0.3.

**Comment by rubenstolk** [comment] 2015-07-22 05:58
This was indeed resolved in `1.0.3` of `paper-header-panel`, however it still doesn't work in (iOS) Safari.

**Comment by valdrinkoshi** [comment] 2015-12-04 18:55
Tested on ios and dialog shows on top of everything
<img width="1216" alt="screen shot 2015-12-04 at 10 56 36 am" src="https://cloud.githubusercontent.com/assets/6173664/11598266/b63b6ba6-9a75-11e5-8d03-db113b474c16.png">

http://jsbin.com/hadolef/6/edit?html,output

Closing this, feel free to re-open if problem persists (with testable example)

**Comment by valdrinkoshi** [comment] 2016-01-05 14:43
For completeness, if `z-index` is set to one of the parents of `paper-dialog`, it might cause wrong rendering http://jsbin.com/hadolef/10/edit?html,output

**Comment by valdrinkoshi** [comment] 2016-01-27 01:43
This issue is caused by the fact that `paper-header-panel` will create a new stacking context as soon as we set `z-index: 0` (because it already has `position: relative`). The `backdropElement` will be added to `body`, so since it has higher `z-index`, it will be on top of the `paper-header-panel` and whatever is inside it. Setting a higher `z-index` to `paper-header-panel` will instead hide the `backdropElement` completely.

For now it's advised to put all overlays in body or outside elements that create their own stacking context
https://elements.polymer-project.org/elements/iron-overlay-behavior

> You should place this element as a child of &lt;body&gt; whenever possible.

**Closed as completed** 2016-01-28 19:44 UTC
Labels: bug, p0 - critical

**Comment by rubenstolk** [comment] 2016-03-04 10:56
Just for the record, the work around is still very useful if you need to have a dialog nested within some other element for data-binding purposes. However notice that since Polymer 1.3, you'll have to use the `Polymer.dom` api for the manipulation to work correctly with styling:

In the `ready` function of your root element:

```
ready () {
    // https://github.com/PolymerElements/paper-dialog/issues/7
    let parent = window.Polymer.dom(this);
    let first = window.Polymer.dom(this.childNodes[0]);
    let dialogs = parent.querySelectorAll('paper-dialog');
    for (let i = dialogs.length - 1; i >= 0; i--) {
      parent.insertBefore(dialogs[i], first);
    }
}
```

I think it would still be useful if a better solution is found for this. Especially because only iOS Safari seems to be the target of this issue...

**Comment by rubenstolk** [comment] 2016-03-29 08:54
Update to be compatible with Polymer 1.4:

```js
attached () {
    this.async(() => {
      // https://github.com/PolymerElements/paper-dialog/issues/7
      window.Polymer.dom.flush();
      let parent = window.Polymer.dom(this);
      let first = window.Polymer.dom(this.childNodes[0]);
      let dialogs = parent.querySelectorAll('paper-dialog');
      for (let i = dialogs.length - 1; i >= 0; i--) {
        parent.insertBefore(dialogs[i], first);
      }
    });
  }
```

**Comment by bhinderbaljeet** [comment] 2016-10-28 09:22
@rubenstolk Thanks for a wonderful working patch

Following snippet is resolving the issue but as you said it has the header issue in IOS.

``` javascript
patchOverlay: function (e) {
  if (e.target.withBackdrop) {
    e.target.parentNode.insertBefore(e.target._backdrop, e.target);
  }
},
```

Then I tried your another solution 

``` javascript
 var dialogs = this.querySelectorAll('paper-dialog');
 var first = this.childNodes[0];
 for (var i = dialogs.length - 1; i >= 0; i--) {
   this.insertBefore(dialogs[i], first);
 }
```

It solves the purpose but all the dialogs are missing their styles that are defined in a particular custom element in my application. Have you faced something like that ? or may be know how to fix that?

**Comment by rubenstolk** [comment] 2016-10-28 10:32
Hi @baljeetbhinder I did face the same issue earlier, not exactly sure how I resolved it but this is the code that is working for me with latest Polymer 1.7.x:

``` js
  const root = Polymer.dom(this.root);
  const first = root.firstChild;
  Polymer.dom(myElement.root)
    .querySelectorAll('paper-dialog')
    .reverse()
    .forEach(dialog => root.insertBefore(dialog, first));
```

**Comment by gitact** [comment] 2016-10-31 15:53
Thanks for the first code! but this _last code doesn't seem to work_ syntactically (cannot use _reverse_ if you don't convert NodeList to Array as below)

```
...
Array.apply(null,   Polymer.dom(myElement.root)
    .querySelectorAll('paper-dialog') )
    .reverse()
    .forEach(dialog => root.insertBefore(dialog, first));
```

By the way...where is defined _myElement_ ? ;-)

**Comment by davebaol** [comment] 2016-10-31 18:56
@gitact 
This works for me 

``` javascript
  var root = Polymer.dom(this.root);
  var first = root.firstChild;
  Array.apply(null, this.querySelectorAll('paper-dialog'))
    .reverse()
    .forEach(dialog => this.insertBefore(dialog, first));
```

**Comment by bhinderbaljeet** [comment] 2016-11-01 09:38
[Just in case anybody needs] It turned out that the cause was usage of paper-scroll-header-panel that has defined

``` css
-webkit-overflow-scrolling: touch;
```

to its main container.
I fixed it by adding this css in my component:

``` css
paper-scroll-header-panel{
    --paper-scroll-header-panel-container:{
        -webkit-overflow-scrolling:auto;
    }
}
```

not sure how correct this statement is but everything seems to work fine now without using any patch.

**Comment by bhinderbaljeet** [comment] 2016-11-08 12:20
@rubenstolk 
thanks again for the solution. I have update polymer to 1.7.0 and applied your latest solution but what should I place as replacement of myElement?

@davebaol  I tried your solution but this is not working in my case trying to figure out why.

**Comment by rubenstolk** [comment] 2016-11-08 12:32
@baljeetbhinder, @gitact I don't know what the fuzz is about, https://www.polymer-project.org/1.0/docs/devguide/local-dom#dom-api clearly mentions that Polymer.dom(...).querySelectorAll will return an array.

**Comment by rubenstolk** [comment] 2016-11-08 12:33
@baljeetbhinder `myElement` would be the element where the dialogs are embedded in...

**Comment by fdasoghe** [comment] 2016-12-06 10:42
The proposed solutions here didn't work for me (Polymer 1.7). I had to move the dialog node under the html body, not just moving it inside the component it's embedded into.

For me worked the solution posted here: http://stackoverflow.com/a/37570263/766695
That is:
```
var body = document.querySelector('body');
Polymer.dom(body).appendChild(this.$.dialogId);
this.$.dialogId.open()
```

Anyway, this bug is still happening in Polymer 1.7, so maybe it should be re-open?

**Comment by hoanganh25991** [comment] 2016-12-11 14:26
A little change on @rubenstolk  comment:
` e.target.parentNode.insertBefore(e.target._backdrop, e.target);`
Should be
` e.target.parentNode.insertBefore(e.target.backdropElement, e.target);`

So the whole answer is:

Add this function to your custom element:
```
// https://github.com/PolymerElements/paper-dialog/issues/7
patchOverlay: function (e) {
  if (e.target.withBackdrop) {
    e.target.parentNode.insertBefore(e.target.backdropElement, e.target);
  }
},
```
Then add `on-iron-overlay-opened`="patchOverlay" to all your `<paper-dialog>`'s

**Comment by valdrinkoshi** [comment] 2016-12-12 18:30
By moving the overlay to become a sibling of the backdrop, you risk to break the styles both for the overlay and its content, as the overlay might reside in another css scope (e.g. inside the shadow root of another element), while the backdrop is always added to `<body>` (in the main document css scope).

**Comment by Alos** [comment] 2016-12-29 13:41
I'm still having this issue with version 2.0-preview.

Adding the patchOverlay function actually worked 😸

**Comment by vedtam** [comment] 2016-12-30 10:06
Unbelievable, such a simple element and function, does it really need this amount of hacking/patching to get it to work, r u serious?? People, better make your own.

By the way, I have the same issue inside a simple iron-page element. Nothing fancy, I am just using the code snippet from the docs, but the dialog shows behind the overlay:

```
  <paper-dialog id="modal" modal>
      <h2>Dialog Title</h2>
      <iron-image src="[[foo]]" alt="" style="width:300px; height:300px;" sizing="contain"></iron-image>
      <div class="buttons">
        <paper-button dialog-confirm autofocus>Tap me to close</paper-button>
      </div>
    </paper-dialog>
```

**Comment by edge0701** [comment] 2017-01-11 13:16
I have a component which has the Polymer.PaperDialogBehavior behavior to create my dialog. I put the event code described above in ready(). No errors. Confirmed event fires. On desktop, I cannot see the overlay (so something has worked). But on two iOS devices, the overlay is still visible, and still above the dialog. Any tips?

**Comment by hoanganh25991** [comment] 2017-01-12 06:12
`pathOverlay` purpose is move the `iron-overlay` in the same parent element with `paper-dialog`
(normally `iron-overlay` under `body`)

you should log on event `e`, try to debug e.target, which it is?

**Comment by edge0701** [comment] 2017-01-12 11:20
The target is the dialog component which has the behavior. And the parentNode is the correct parent node. I just tried changing it to a normal paper-dialog with exact code as above. Still not working on iDevice.

My app structure may have something to do with it?
iron-pages on top level app component, with 2 components (auth stuff route & logged-in route). I then have a paper-drawer-panel in the logged-in route. Inside that paper-drawer panel is an iron-pages component for each major category in the app. Then iron-pages within major category, with sub components.

**Comment by hoanganh25991** [comment] 2017-01-13 02:56
I think your code is fine, don't know why it not work on iDevice,.
I haven't tried on iDevice, only with Chrome browser on android-phone.

**Comment by julcod** [comment] 2017-01-14 04:45
For me none of the hacks giving works.. For me the dialog is launched from a sidebar (which means the dialog parent is not fullbleed)

- Hack of  @rubenstolk  (move backdrop behind overlay) doesn't work, the backdrop fit to the sidebar and disapear
- Hack of @think01 (the opposite), broke all binding and even from the dialog.

Only one solution... create a wrapper of app-dialog with my own backdrop

`div id="backdrop"></div>`

Then, deactivating the dialog backdrop

`this.$.dialog.backdropElement.toggleAttribute("hidden",true)`

And on `iron-resize` 

```
var dialog = this.$.dialog
var backdrop = this.$.backdrop
backdrop.style.width = this.opened ? window.innerWidth + "px" : "0px"
backdrop.style.height = this.opened ? window.innerHeight + "px" : "0px"
backdrop.style.zIndex = this.opened ? dialog.backdropElement.style.zIndex : "0"
```
It's ugly ... but it works....

**Comment by valdrinkoshi** [comment] 2017-01-16 23:06
If one of the parents of a dialog creates a new stacking context, all its children (dialog included) will be trapped in it, meaning that parent layout will be the containing block for all the children, and crop any overflow it it has `overflow: auto|scroll|none` rule applied.
This makes it hard for the element author to use dialogs or overlays in general in their components, as these elements might be contained in a node that creates a new stacking context.

This is a limitation of the platform, we don't have yet an APIs to add nodes on the [Top Layer](https://fullscreen.spec.whatwg.org/#top-layer), hence we have to find other ways around.
I've prepared a codelab to show more in details this problem https://codelabs.developers.google.com/codelabs/building-custom-overlays/, step 4 describes more in detail the stacking context trap.

What I'm trying to say here is: there is not silver bullet solution for this issue.
As soon as we have to move a dialog in a stacking-context-safe node we lose style encapsulation, and we might break the data bindings.

The solution provided by @graphy75 (hide the singleton backdropElement and have a custom backdrop for each overlay) would partially solve the problem, as your dialog might still be cropped or scroll together with the other content when contained in a scrollable parent node that creates a stacking context (see the step 4 of the codelab or feel free to ask for other examples).

**Comment by Sinjins** [comment] 2017-02-27 02:29
Ugh...I'm finding this issue to be kind of brutal to work around.  A bit of a nasty surprise I have to say while beta testing in iOS.

**Comment by iShafayet** [comment] 2017-05-30 05:49
I had to modify the solution provided by @davebaol  the following way in order for it to work on Polymer 2.0
```
        const root = Polymer.dom(this.root);
        const first = root.firstChild;
        Array.from(root.querySelectorAll('paper-dialog'))
          .reverse()
          .forEach(dialog => root.insertBefore(dialog, first));

```

**Comment by ldn4869** [comment] 2017-06-25 17:48
Thanks! The solution provided by @rubenstolk also work on Polymer 2.0, And  if someone like me just want to make all the `<paper-dialog>` elements  behave like @rubenstolk 's method  , maybe you could change the source code in "paper-dialog.html" like this:
```
listeners: {
      'neon-animation-finish': '_onNeonAnimationFinish',
      //解决 bug: https://github.com/PolymerElements/paper-dialog/issues/7
      'iron-overlay-opened': '_patchOverlay'
    },
```
and add function:
```
_patchOverlay: function(e) {
      // console.log('haha',e.target)
      if (e.target.withBackdrop) {
        e.target.parentNode.insertBefore(e.target.backdropElement, e.target);
      }
    }
```

**Comment by ldn4869** [comment] 2017-06-25 17:50
Thanks! The solution provided by @rubenstolk also work on Polymer 2.0, And if someone like me just want to make all the <paper-dialog> elements behave like @rubenstolk 's method , maybe you could change the source code in "paper-dialog.html" like this:

```
listeners: {
      'neon-animation-finish': '_onNeonAnimationFinish',
      //解决 bug: https://github.com/PolymerElements/paper-dialog/issues/7
      'iron-overlay-opened': '_patchOverlay'
    },
```
and add function in "paper-dialog.html":

```
_patchOverlay: function(e) {
      if (e.target.withBackdrop) {
        e.target.parentNode.insertBefore(e.target.backdropElement, e.target);
      }
    }
```

**Comment by ldn4869** [comment] 2017-06-25 17:51
Thanks! The solution provided by @rubenstolk also work on Polymer 2.0, And if someone like me just want to make all the `<paper-dialog>` elements behave like @rubenstolk 's method , maybe you could change the source code in "paper-dialog.html" like this:

```
listeners: {
      'neon-animation-finish': '_onNeonAnimationFinish',
      //解决 bug: https://github.com/PolymerElements/paper-dialog/issues/7
      'iron-overlay-opened': '_patchOverlay'
    },
```
and add function in "paper-dialog.html":

```
_patchOverlay: function(e) {
      if (e.target.withBackdrop) {
        e.target.parentNode.insertBefore(e.target.backdropElement, e.target);
      }
    }
```
instead of add `on-iron-overlay-opened="patchOverlay"` to all your `<paper-dialog>`'s

**Comment by Matheus-Ribeiro95** [comment] 2017-06-29 14:48
@ldn4869 Really nice.
Worked, Polymer 2.

**Comment by BorntraegerMarc** [comment] 2017-07-18 10:21
@ldn4869 Your solution has not worked for me unfortunately.... How can this still be an issue with polymer 2

**Comment by BorntraegerMarc** [comment] 2017-07-18 10:36
I went with this fix https://github.com/PolymerElements/paper-dialog/issues/152#issuecomment-312139650 now

**Comment by NaqashPixy** [comment] 2017-07-21 13:38
Set property "alwaysOnTop=true" to your secondary dialog

**Comment by valdrinkoshi** [comment] 2018-05-16 21:53
@ldn4869 @rubenstolk if the method you suggested works for you, I'd suggest to have a single listener on the main document for the `iron-overlay-opened` event instead of adding it in each dialog. This event bubble and is composed, so you will be able to listen for it from the main document, e.g.
```js
document.addEventListener('iron-overlay-opened', function moveBackdrop(event) {
  var dialog = Polymer.dom(event).rootTarget;
  if (dialog.withBackdrop) {
    dialog.parentNode.insertBefore(dialog.backdropElement, dialog);
  }
});

**Comment by LoganxDev** [comment] 2018-08-19 22:56
I've still had issues with the backdrop covering the entire screen and content being placed in front of it.   I couldn't seem to just directly grab the document body and work with it so the code I used that seemed to work is below.

```
if (e.target.withBackdrop) {
    let parent = e.target.getRootNode().host;
    while (parent !== undefined && parent !== null) {
        if (parent && parent.parentNode === null) {
                    parent = parent.getRootNode().host ? parent.getRootNode().host : parent;
        } else {
                    parent = parent.parentNode;
        }
        if (parent === document.body) {
                    parent.appendChild(e.target);
                    return;
        }
    }
}
```

Hope this helps anyone still experiencing issues.

**Comment by jmanueltl** [comment] 2018-11-29 15:45
@ldn4869  very nice, thanks,
Its work for me.
