### ISSUE TITLE
Forms floating labels inside paper-dialog cause a blink on x-axis when paper-dialog-scrollable is used

### ISSUE THREAD

**Issue by fakiolinho** [PolymerElements/paper-dialog#88] opened 2016-02-09 09:54 UTC
This happens when a form with floating labels is used inside a `paper-dialog` dialog with `paper-dialog-scrollable` element. Whenever user types sth for the first time in any field and the label movement takes place a scrolling bar on x-axis appears for an eye-blink (till the label finishes its movement). This does not happen when `paper-dialog-scrollable` is not used. I guess it happens probably because the `<div id="scrollable">..</div>` inside `paper-dialog-scrollable` element has `overflow: auto;`. Maybe the best solution here would be `overflow-y: auto; overflow-x: hidden;` which seems to solve this overflow issue. I am using Polymer 1.2.4 tested on Chrome 48.0.2564.103 and Firefox 44.0.1

**Comment by valdrinkoshi** [comment] 2016-02-09 18:15
I cannot reproduce it with `paper-dialog-scrollable` master branch http://jsbin.com/teqadif/2/edit?html,output
![dialog-input](https://cloud.githubusercontent.com/assets/6173664/12925974/ec8b21b8-cf15-11e5-9665-a0aecb3062f2.gif)

Closing this, please comment with an example/jsbin to reproduce the issue, and we'll re-open it if necessary ;)

Update: `v1.1.1` of `paper-dialog-scrollable` has just been published (no need to get it from the master branch)

**Closed as completed by valdrinkoshi** 2016-02-09 18:15 UTC

**Comment by fakiolinho** [comment] 2016-02-09 18:39
Thanks for your efforts the truth is i updated earlier my dependencies and now i don't see this. Anyway thanks for your response!!
