### ISSUE TITLE
Dialog not centered until window resize

### ISSUE THREAD

**Issue by retrohacker** [PolymerElements/paper-dialog#36] opened 2015-08-31 12:45 UTC
![compressed](https://cloud.githubusercontent.com/assets/1081565/9578892/d41a05ce-4fbb-11e5-9600-c8175119b034.gif)

I'm adding the dialog to the DOM using backbone. I add it as "opened" so that it renders.

Code:

I reduced the code down to this. It seems that the issue is hidden when you reduce the number of characters between the `<p>` tags.

`index.html`

``` html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- IMPORT POLYMER DEPS -->
    <link rel="import" href="bower_components/polymer/polymer.html">
    <link rel="import" href="bower_components/paper-styles/paper-styles.html">
    <link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html">
    <link rel="import" href="bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="bower_components/iron-icons/image-icons.html">
    <link rel="import" href="bower_components/paper-fab/paper-fab.html">
    <link rel="import" href="bower_components/paper-dialog/paper-dialog.html">
    <link rel="import" href="bower_components/paper-dialog-behavior/paper-dialog-behavior.html">
    <link rel="import" href="bower_components/neon-animation/neon-animation.html">
    <link rel="import" href="bower_components/iron-overlay-behavior/iron-overlay-behavior.html">
    <link rel="import" href="bower_components/iron-selector/iron-selector.html">
    <link rel="import" href="bower_components/iron-fit-behavior/iron-fit-behavior.html">
    <script type="text/javascript" src="bower_components/web-animations-js/web-animations.min.js"></script>
    <!-- END POLYMER -->

    <!-- IMPORT BACKBONE DEPS -->
    <script type="text/javascript" src="bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="bower_components/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="bower_components/backbone/backbone-min.js"></script>
    <!-- END BACKBONE DEPS -->

  </head>
  <body class="fullbleed">
    <div id="popup"></div>
    <div id="actionItems"></div>
    <script type="text/template" id="buttonTemplate">
      <paper-fab icon="image:add-to-photos"></paper-fab>
    </script>
    <script type="text/template" id="dialogTemplate">
      <paper-dialog opened>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </paper-dialog>
    </script>
    <script type="text/javascript" src="example.js"></script>
  </body>
</html>
```

`example.js`

``` js
var Popup = Backbone.View.extend({
  el: '#popup',
  initialize: function() {
    this.render()
  },
  template:_.template($("#dialogTemplate").html()),
  render: function() {
    this.$el.html(this.template)
  }
})

var ActionItems = Backbone.View.extend({
  el: '#actionItems',
  initialize: function() {
    this.render()
  },
  events: {
    "click": "openDialogue"
  },
  openDialogue: function(e) {
    var createDeck = new Popup()
  },
  template:_.template($("#buttonTemplate").html()),
  render: function() {
    this.$el.html(this.template)
  }
})

var popup = new ActionItems()
```

**Comment by zoechi** [comment] 2015-08-31 13:27
You might need to call `notifyResize()` on the dialog to make it update it's layout.

**Comment by andrewebdev** [comment] 2015-10-07 18:16
so the solution mentioned by @zoechi works, but with me in polymer I had to wait before opening the dialog. So I called the .open() method inside .async().

**Comment by rvraaphorst** [comment] 2015-11-12 08:55
Could this be a simple solution? http://stackoverflow.com/questions/33650752/center-paper-dialog-upon-opening/33667559#33667559

**Comment by valdrinkoshi** [comment] 2015-12-07 22:03
@rvraaphorst unfortunately that change won't help.
The problem is caused by `IronFitBehavior` which calculates the new position too early. This should be fixed either in `IronOverlayBehavior`, by postponing this calculation to a later moment (e.g. in `attached` instead of `ready` function).

**Comment by valdrinkoshi** [comment] 2015-12-07 22:03
Closing this, as is a duplicate of https://github.com/PolymerElements/paper-dialog-behavior/issues/41

**Closed as completed by valdrinkoshi** 2015-12-07 22:03 UTC
