### ISSUE TITLE
Scroll wheel events cause the underlying document to scroll

### ISSUE THREAD

**Issue by davidgiven** [PolymerElements/paper-dialog#98] opened 2016-03-26 13:32 UTC
If you move the scroll wheel when a dialogue is open, and the document behind the dialogue is scrollable, then the document scrolls.

You can see this happen in the demo.

https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html

Resize the browser so that a scrollbar appears, then pop up a dialogue and try scrolling.

If the dialogue itself contains a scrollable area, and you're not at the end of it, then the mouse wheel causes the dialogue's scrollable area to move. But once you reach the end of the scrollable area the events are passed on to the underlying document again.

I would expect the dialogue to swallow all scrollwheel events when the mouse is over the dialogue (and in the case of modal dialogues, all scrollwheel events full stop).

Observed on Chrome and Firefox.

**Comment by valdrinkoshi** [comment] 2016-03-28 16:46
Hi @davidgiven, closing this as it is a duplicate of https://github.com/PolymerElements/iron-overlay-behavior/issues/140

**Closed as completed by valdrinkoshi** 2016-03-28 16:46 UTC
