### ISSUE TITLE
Modal Paper dialog sits behind the iron-overlay-backdrop [2.0-preview]

### ISSUE THREAD

**Issue by Ado77** [PolymerElements/paper-dialog#148] opened 2017-04-26 00:35 UTC
### Description
Modal Paper dialog sits behind the iron-overlay-backdrop for 2.0-preview

### Expected outcome

I would expect the paper-dialog to be clickable

### Actual outcome

Iron-overlay-backdrop prevents clicking on dialog

### Steps to reproduce
1. polymer init polymer-2-starter-kit
2. bower install paper-dialog#2.0-preview
3. add paper-dialog to view1 with modal and opened="true"

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by runia1** [comment] 2017-04-27 04:23
I have also experienced this behavior.  Moving the dialog out of `<my-view1>` into `<my-app>` worked, however that shouldn't be necessary.

**Comment by NicolaiSchmid** [comment] 2017-04-30 17:00
+1

**Comment by valdrinkoshi** [comment] 2017-05-01 17:14
Duplicate of https://github.com/PolymerElements/iron-overlay-behavior/issues/208

This is a known limitation of overlays, see more details on how we plan to solve this issue here https://github.com/PolymerElements/iron-overlay-behavior/issues/208#issuecomment-293349138

**Closed as completed by valdrinkoshi** 2017-05-01 17:14 UTC
