### ISSUE TITLE
Dialog isn't centered when inside paper-header-panel

### ISSUE THREAD

**Issue by Whyser** [PolymerElements/paper-dialog#34] opened 2015-08-25 20:00 UTC
As the topic says; the dialog won't get centered when inside an paper-header-panel with a navigation panel. It seems the dialog doesn't consider the width of the navigation-menu when calculating the center. If the windows is resized and the navigation menu collapses the center of the dialog will be correct. Also, if there's anything else besides the dialog in the `<template>..other stuff here...</template>` they will also be offset from the center when the dialog is shown (not before).

![notcenter](https://cloud.githubusercontent.com/assets/6816092/9477855/a16d7340-4b74-11e5-976e-24fa78bfe04b.png)

![center](https://cloud.githubusercontent.com/assets/6816092/9477859/a66175ea-4b74-11e5-8ad5-72b4fd9588cd.png)

**Comment by valdrinkoshi** [comment] 2015-12-07 20:18
Hi @Whyser, dialogs are centered according to the whole window frame, so the rendering you see is correct / by design.
Could you provide an example (jsbin, jsfiddle..) on this part:

> Also, if there's anything else besides the dialog in the `<template>..other stuff here...</template>` they will also be offset from the center when the dialog is shown (not before).

**Comment by valdrinkoshi** [comment] 2015-12-07 20:33
For the positioning, we should support this kind of feature, a.k.a. assign to the dialog a target parent element as reference for positioning. I'll mark this as a feature request/enhancement ;)
cc @cdata.

**Comment by Whyser** [comment] 2015-12-07 21:00
Thank you @valdrinkoshi for confirming it as intended behavior (and a possible enhancement)! Regarding the other issue; I don't really have this code any more, but I will see if I can re-create what I was talking about (it was quite some time ago ;) ).

EDIT: Couldn't re-create the other issue i mentioned. :)

**Comment by valdrinkoshi** [comment] 2015-12-09 02:11
That's good news :)

I've looked into `iron-fit-behavior` and noticed there is a [property `fitInto`](https://elements.polymer-project.org/elements/iron-fit-behavior#fitInto) which can be used to center the dialog according to another element.
So here an example of the drawer with a dialog centered according to `main` http://jsbin.com/cunasu/1/edit?html,output

``` javascript
document.querySelector('paper-dialog').fitInto = document.querySelector('#dialog-container'); 
```

**Closed as completed by valdrinkoshi** 2015-12-09 02:11 UTC
Labels: enhancement
