### ISSUE TITLE
Modal shown by default if placed inside `dom-if` template

### ISSUE THREAD

**Issue by teckays** [PolymerElements/paper-dialog#14] opened 2015-06-12 08:12 UTC
The modal dialog renders if placed inside `<template is="dom-if" if=""></template>` should it be this way?

**Comment by marcus7777** [comment] 2015-06-29 13:35
If so it not working same as `dialog.open` modal if load with mod-if no model back ground

**Comment by morethanreal** [comment] 2015-07-14 18:11
This seems to be caused by https://github.com/Polymer/polymer/issues/2037

**Comment by valdrinkoshi** [comment] 2015-12-04 00:36
Got fixed by https://github.com/Polymer/polymer/commit/26112859d2ae6916f2066acafbf6c30f0fede797 (same fix of https://github.com/Polymer/polymer/issues/2037)
Closing this

**Closed as completed by valdrinkoshi** 2015-12-04 00:36 UTC
Labels: bug
