### ISSUE TITLE
iron-overlay sometimes covering the paper-dialog

### ISSUE THREAD

**Issue by mrherndon** [PolymerElements/paper-dialog#101] opened 2016-04-15 15:05 UTC
### Description

I bower updated yesterday, for the first time in about two months.  And several things broke for me.  I found most things fairly easy, but this one is driving me up a wall. 

 Some modal paper-dialogs preform as expected, but paper-dialogs that are a nested down a few elements show up under the iron-overlay.  The z-indexes are correct, and modifying them changes nothing.  

### Expected outcome

That the iron-overlay will show up under the modal paper-dialog.
![image](https://cloud.githubusercontent.com/assets/8726819/14565221/a5349b9c-02ef-11e6-9901-73f4654a2ed6.png)

### Actual outcome

The iron-overlay is appearing above the paper-dialog.
![image](https://cloud.githubusercontent.com/assets/8726819/14565247/bdba6b10-02ef-11e6-9c39-0063ec740a1f.png)

### Live Demo

http://raywebdev.net/getInvolved/
Clicking the "Contact" button produces a paper-dialog with the desired outcome.
Clicking the "Donate" button produces the undesired results.
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [ ] Safari 7 - we serve html only for this
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by valdrinkoshi** [comment] 2016-04-18 17:16
Hi @mrherndon, this problem is caused by the way [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) works (see this example http://jsbin.com/lemufe/4/edit?html,output).
The `paper-dialog` of "Contact" is a sibling of the `iron-overlay-backdrop`, while the `paper-dialog` of "Donate" is inside elements that create a new stacking context. Since `iron-overlay-backdrop` is added into `document.body`, it will be in a different stacking context, which is on top of the one of your dialog.
This is a known limitation of overlays, and as mentioned in the [iron-overlay-behavior documentation](https://elements.polymer-project.org/elements/iron-overlay-behavior):

> You must ensure no element has a stacking context with a higher z-index than its parent stacking context. You should place this element as a child of &lt;body&gt; whenever possible.

**Closed as completed by valdrinkoshi** 2016-04-18 17:16 UTC

**Comment by mrherndon** [comment] 2016-04-18 17:18
Thank you for the help.  I couldn't find it in the documentation.
