### ISSUE TITLE
Dialog in Dialog causes unwanted scroll.

### ISSUE THREAD

**Issue by TimWillis** [PolymerElements/paper-dialog#38] opened 2015-09-23 12:42 UTC
I have a dialog inside a dialog that I dynamically position(because they don't position correctly when a dialog has scrolling). When I do this it sets the parents dialog scroll to 0,0. I don't want this as it takes my child dialog out of visibility. The issue is when this.refit is called in Iron-oerlay-behavior found in this function:
_onIronResize: function() {
      if (this._squelchNextResize) {
        this._squelchNextResize = false;
        return;
      }
      if (this.opened) {
          this.refit();
      }
    }

I can comment this.refit() out to fix unwanted behavior.

Thanks
Tim

**Comment by notwaldorf** [comment] 2015-09-28 19:18
@TimWillis What do you mean by "dialogs don't position correctly when they have scrolling"? Do you have a jsbin or a code snippet that can repro this bug? Thanks!

**Comment by TimWillis** [comment] 2015-09-29 13:22
I don't have a jsbin or an easy to repro example, but I believe it happens
when the content, including the inner dialog, of the outer dialog is a
template for-each.

On Mon, Sep 28, 2015 at 3:18 PM, Monica Dinculescu <notifications@github.com

**Comment by valdrinkoshi** [comment] 2015-12-08 00:06
Hi @TimWillis, I've tried to simulate a scenario you described and I cannot reproduce the issue http://jsfiddle.net/valdrinkoshi/Lhuvtk80/
When you resize, the scrollTop gets updated because the new width/height permits to better layout the content of the dialog. 
e.g. more width will reduce the dialog's scroll height.

Are you asking for `paper-dialog` to keep the scroll position on resize?

**Comment by valdrinkoshi** [comment] 2016-01-28 23:47
Closing this, feel free to re-open if the issue persists (please provide a jsbin/example, check https://github.com/PolymerElements/paper-dialog/blob/master/CONTRIBUTING.md to get you started)

**Closed as completed by valdrinkoshi** 2016-01-28 23:47 UTC
Labels: pending-response
